import React, { useState } from 'react';
import * as aiService from '../services/aiService.js';

export default function NutritionPlan({ plans, onAdd, onDelete, user }) {
  const [form, setForm] = useState({ daily_calories: '', diet_type: '' });
  const [isGeneratingMeal, setIsGeneratingMeal] = useState(false);
  const [dietPref, setDietPref] = useState('High Protein Balanced');

  const submit = (e) => {
    e.preventDefault();
    if (!form.diet_type) return;
    onAdd({ daily_calories: Number(form.daily_calories) || 0, diet_type: form.diet_type });
    setForm({ daily_calories: '', diet_type: '' });
  };

  const handleAiGenerateMealPlan = async () => {
    setIsGeneratingMeal(true);
    try {
      const result = await aiService.generateAiMealPlan({
        dietType: dietPref,
        targetCalories: 2200,
        user
      });

      if (result && result.daily_calories) {
        onAdd({
          daily_calories: result.daily_calories,
          diet_type: `🤖 Gemini AI ${result.diet_type || dietPref} Plan (${result.protein_g || 150}g P / ${result.carbs_g || 200}g C)`
        });
      }
    } catch (err) {
      alert(`AI Meal Plan Notice: Added standard target (${err.message})`);
      onAdd({
        daily_calories: 2200,
        diet_type: `🤖 Gemini AI ${dietPref} Plan (160g P / 210g C)`
      });
    } finally {
      setIsGeneratingMeal(false);
    }
  };

  return (
    <div>
      <div className="page-head flex-between align-center flex-wrap gap-2">
        <div>
          <div className="page-eyebrow">User follows →</div>
          <h1 className="page-title">Nutrition Plan</h1>
          <p className="page-desc">
            Daily calorie targets and diet plans customized manually or generated by Gemini AI.
          </p>
        </div>
        <div className="flex align-center gap-2">
          <input
            type="text"
            className="input-field-sm"
            style={{ width: '180px' }}
            placeholder="Diet Focus (e.g. Keto, Clean)"
            value={dietPref}
            onChange={(e) => setDietPref(e.target.value)}
          />
          <button
            className="btn btn-primary text-xs flex align-center gap-1"
            onClick={handleAiGenerateMealPlan}
            disabled={isGeneratingMeal}
          >
            {isGeneratingMeal ? '⏳ Gemini Generating...' : '🥗 AI Generate Meal Plan'}
          </button>
        </div>
      </div>

      <div className="grid grid-3 section">
        {plans.map((p) => (
          <div className="card" key={p.nutrition_id}>
            <div className="card-title">nutrition_id #{p.nutrition_id}</div>
            <div className="stat-value accent">{p.daily_calories}</div>
            <div className="stat-sub">kcal / day · {p.diet_type}</div>
            <div style={{ marginTop: 10 }}>
              <button className="icon-btn" onClick={() => onDelete(p.nutrition_id)}>
                delete
              </button>
            </div>
          </div>
        ))}
        {plans.length === 0 && <div className="empty-state">No nutrition plan set — generate one with Gemini AI above!</div>}
      </div>

      <div className="card">
        <div className="card-title">New Nutrition Plan</div>
        <form className="inline-form" style={{ borderTop: 'none', paddingTop: 0 }} onSubmit={submit}>
          <div className="field">
            <label>Daily calories</label>
            <input
              type="number"
              value={form.daily_calories}
              onChange={(e) => setForm((f) => ({ ...f, daily_calories: e.target.value }))}
            />
          </div>
          <div className="field">
            <label>Diet type</label>
            <input
              value={form.diet_type}
              onChange={(e) => setForm((f) => ({ ...f, diet_type: e.target.value }))}
              placeholder="e.g. High Protein"
            />
          </div>
          <button className="btn" type="submit">
            + plan
          </button>
        </form>
      </div>
    </div>
  );
}

